/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/auth/dangki`; params?: Router.UnknownInputParams; } | { pathname: `/auth/quenmk`; params?: Router.UnknownInputParams; } | { pathname: `/home/datngay`; params?: Router.UnknownInputParams; } | { pathname: `/home/datphong`; params?: Router.UnknownInputParams; } | { pathname: `/home/huyphong`; params?: Router.UnknownInputParams; } | { pathname: `/home/lich`; params?: Router.UnknownInputParams; } | { pathname: `/home/spsn`; params?: Router.UnknownInputParams; } | { pathname: `/home/thanhtoan`; params?: Router.UnknownInputParams; } | { pathname: `/home/timkiem`; params?: Router.UnknownInputParams; } | { pathname: `/home/trangchu`; params?: Router.UnknownInputParams; } | { pathname: `/home/ttphong`; params?: Router.UnknownInputParams; } | { pathname: `/profile/hoso`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/dangki`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/quenmk`; params?: Router.UnknownOutputParams; } | { pathname: `/home/datngay`; params?: Router.UnknownOutputParams; } | { pathname: `/home/datphong`; params?: Router.UnknownOutputParams; } | { pathname: `/home/huyphong`; params?: Router.UnknownOutputParams; } | { pathname: `/home/lich`; params?: Router.UnknownOutputParams; } | { pathname: `/home/spsn`; params?: Router.UnknownOutputParams; } | { pathname: `/home/thanhtoan`; params?: Router.UnknownOutputParams; } | { pathname: `/home/timkiem`; params?: Router.UnknownOutputParams; } | { pathname: `/home/trangchu`; params?: Router.UnknownOutputParams; } | { pathname: `/home/ttphong`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/hoso`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `/auth/dangki${`?${string}` | `#${string}` | ''}` | `/auth/quenmk${`?${string}` | `#${string}` | ''}` | `/home/datngay${`?${string}` | `#${string}` | ''}` | `/home/datphong${`?${string}` | `#${string}` | ''}` | `/home/huyphong${`?${string}` | `#${string}` | ''}` | `/home/lich${`?${string}` | `#${string}` | ''}` | `/home/spsn${`?${string}` | `#${string}` | ''}` | `/home/thanhtoan${`?${string}` | `#${string}` | ''}` | `/home/timkiem${`?${string}` | `#${string}` | ''}` | `/home/trangchu${`?${string}` | `#${string}` | ''}` | `/home/ttphong${`?${string}` | `#${string}` | ''}` | `/profile/hoso${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/auth/dangki`; params?: Router.UnknownInputParams; } | { pathname: `/auth/quenmk`; params?: Router.UnknownInputParams; } | { pathname: `/home/datngay`; params?: Router.UnknownInputParams; } | { pathname: `/home/datphong`; params?: Router.UnknownInputParams; } | { pathname: `/home/huyphong`; params?: Router.UnknownInputParams; } | { pathname: `/home/lich`; params?: Router.UnknownInputParams; } | { pathname: `/home/spsn`; params?: Router.UnknownInputParams; } | { pathname: `/home/thanhtoan`; params?: Router.UnknownInputParams; } | { pathname: `/home/timkiem`; params?: Router.UnknownInputParams; } | { pathname: `/home/trangchu`; params?: Router.UnknownInputParams; } | { pathname: `/home/ttphong`; params?: Router.UnknownInputParams; } | { pathname: `/profile/hoso`; params?: Router.UnknownInputParams; };
    }
  }
}
